// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UzMarket.RepositoryLayer.DataBase;

#nullable disable

namespace UzMarket.RepositoryLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718160440_B")]
    partial class B
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CITY");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_DIFAULT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("POSTAL_CODE");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("REGION");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("STREET");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SYS_ADDRESS");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SYS_CART");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.CartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("CART_ID");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTITY");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("SYS_CART_ITEM");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.Property<long?>("ParentCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("PARENT_CATEGORY_ID");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("SYS_CATEGORY");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Favorite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("SYS_FAVORITE");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ORDER_DATE");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("ORDER_STATUS_ID");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("integer")
                        .HasColumnName("SHIPPING_ADDRESS_ID");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StatusConst")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("SYS_ORDER");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("ORDER_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("PRICE");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("QUANTITY");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("SYS_ORDER_ITEM");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("AMOUNT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("ORDER_ID");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("PAYMENT_METHOD_ID");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("TRANSACTION_DATE");

                    b.HasKey("Id");

                    b.ToTable("SYS_PAYMENT");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("PRICE");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("STOCK_QUANTITY");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("SUPPLIER_ID");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("SYS_PRODUCT");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.ProductImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IMAGE_URL");

                    b.Property<bool>("MainPic")
                        .HasColumnType("boolean")
                        .HasColumnName("MAIN_PIC");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("SORT_ORDER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("SYS_PRODUCT_IMAGE");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("COMMENT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RatingId")
                        .HasColumnType("integer")
                        .HasColumnName("RATING");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("SYS_REVIEW");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ADDRESS");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("integer")
                        .HasColumnName("CREATED_USER_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("PASSWORD");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MODIFIED_AT");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("MODIFIED_USER_ID");

                    b.Property<string>("PassportSeries")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("PASSPORT_SERIES");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("Pinfl")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("PINFL");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("SHORT_NAME");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS_ID");

                    b.Property<int>("StatusIdConst")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("SYS_USER");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Address", b =>
                {
                    b.HasOne("UzMarket.RepositoryLayer.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Cart", b =>
                {
                    b.HasOne("UzMarket.RepositoryLayer.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.CartItem", b =>
                {
                    b.HasOne("UzMarket.RepositoryLayer.Entity.Cart", "Cart")
                        .WithMany("Tables")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzMarket.RepositoryLayer.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Category", b =>
                {
                    b.HasOne("UzMarket.RepositoryLayer.Entity.Category", "ParentCategory")
                        .WithMany("GetListCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Favorite", b =>
                {
                    b.HasOne("UzMarket.RepositoryLayer.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzMarket.RepositoryLayer.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Order", b =>
                {
                    b.HasOne("UzMarket.RepositoryLayer.Entity.Address", "Address")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzMarket.RepositoryLayer.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.OrderItem", b =>
                {
                    b.HasOne("UzMarket.RepositoryLayer.Entity.Order", "Order")
                        .WithMany("Tables")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzMarket.RepositoryLayer.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Product", b =>
                {
                    b.HasOne("UzMarket.RepositoryLayer.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzMarket.RepositoryLayer.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.ProductImage", b =>
                {
                    b.HasOne("UzMarket.RepositoryLayer.Entity.Product", "Product")
                        .WithMany("Tables")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Cart", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Category", b =>
                {
                    b.Navigation("GetListCategories");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Order", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("UzMarket.RepositoryLayer.Entity.Product", b =>
                {
                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
